-- PharmaDerm — Full Countries Seed
-- Run AFTER seed.sql (which already inserts the 30 base countries)
-- This file adds additional countries and any currencies they require
-- All statements are idempotent (ON CONFLICT DO NOTHING)
-- =====================================================================

-- =====================================================================
-- ADDITIONAL CURRENCIES  (not in seed.sql)
-- =====================================================================
INSERT INTO currencies (code, name, symbol, exchange_rate_to_usd) VALUES
  ('AUD', 'Dólar australiano',      'A$',    1.530000),
  ('NZD', 'Dólar neozelandés',      'NZ$',   1.640000),
  ('SGD', 'Dólar de Singapur',      'S$',    1.340000),
  ('HKD', 'Dólar de Hong Kong',     'HK$',   7.820000),
  ('TWD', 'Dólar taiwanés',         'NT$',  31.500000),
  ('CNY', 'Yuan chino',             '¥',     7.240000),
  ('KRW', 'Won surcoreano',         '₩',  1320.000000),
  ('INR', 'Rupia india',            '₹',    83.200000),
  ('IDR', 'Rupia indonesia',        'Rp', 15600.000000),
  ('MYR', 'Ringgit malayo',         'RM',    4.720000),
  ('THB', 'Baht tailandés',         '฿',    35.500000),
  ('PHP', 'Peso filipino',          '₱',    56.700000),
  ('VND', 'Dong vietnamita',        '₫', 24300.000000),
  ('PKR', 'Rupia pakistaní',        '₨',   279.000000),
  ('BDT', 'Taka bangladesí',        '৳',   110.000000),
  ('LKR', 'Rupia de Sri Lanka',     '₨',   320.000000),
  ('NPR', 'Rupia nepalesa',         '₨',   133.000000),
  ('AED', 'Dírham emiratí',         'د.إ',   3.670000),
  ('SAR', 'Riyal saudí',            '﷼',    3.750000),
  ('QAR', 'Riyal catarí',           '﷼',    3.640000),
  ('KWD', 'Dinar kuwaití',          'د.ك',   0.307000),
  ('BHD', 'Dinar bareiní',          '.د.ب',  0.376000),
  ('OMR', 'Rial omaní',             'ر.ع.',  0.385000),
  ('JOD', 'Dinar jordano',          'JD',    0.709000),
  ('ILS', 'Séquel israelí',         '₪',    3.740000),
  ('TRY', 'Lira turca',             '₺',   32.500000),
  ('ZAR', 'Rand sudafricano',       'R',    18.900000),
  ('NGN', 'Naira nigeriana',        '₦', 1450.000000),
  ('KES', 'Chelín keniano',         'KSh',  130.000000),
  ('EGP', 'Libra egipcia',          '£',    48.500000),
  ('MAD', 'Dírham marroquí',        'MAD',  10.020000),
  ('DZD', 'Dinar argelino',         'DA',  134.500000),
  ('TND', 'Dinar tunecino',         'TND',   3.130000),
  ('GHS', 'Cedi ghanés',            'GH₵',  15.800000),
  ('XOF', 'Franco CFA (UEMOA)',     'CFA', 615.000000),
  ('XAF', 'Franco CFA (CEMAC)',     'FCFA',615.000000),
  ('SEK', 'Corona sueca',           'kr',   10.510000),
  ('NOK', 'Corona noruega',         'kr',   10.650000),
  ('DKK', 'Corona danesa',          'kr',    6.890000),
  ('PLN', 'Esloti polaco',          'zł',    3.980000),
  ('CZK', 'Corona checa',           'Kč',   23.100000),
  ('HUF', 'Forinto húngaro',        'Ft',  365.000000),
  ('RON', 'Leu rumano',             'lei',   4.580000),
  ('BGN', 'Lev búlgaro',            'лв',   1.810000),
  ('HRK', 'Kuna croata (histórico)','kn',    6.640000),
  ('RSD', 'Dinar serbio',           'дин',108.000000),
  ('UAH', 'Hryvnia ucraniana',      '₴',   39.500000),
  ('ISK', 'Corona islandesa',       'kr',  138.000000),
  ('HUF', 'Forinto húngaro',        'Ft',  365.000000),
  ('MXN', 'Peso mexicano',          '$',    17.150000),  -- already in seed, safety
  ('GTQ', 'Quetzal guatemalteco',   'Q',     7.770000),
  ('HNL', 'Lempira hondureño',      'L',    24.700000),
  ('NIO', 'Córdoba nicaragüense',   'C$',   36.700000),
  ('CRC', 'Colón costarricense',    '₡',  517.000000),
  ('JMD', 'Dólar jamaiquino',       'J$',  156.000000),
  ('TTD', 'Dólar de Trinidad',      'TT$',   6.780000),
  ('BBD', 'Dólar de Barbados',      'Bds$',  2.000000),
  ('XCD', 'Dólar del Caribe Oriental','$',   2.700000),
  ('HTG', 'Gourde haitiano',        'G',   131.000000),
  ('BSD', 'Dólar bahameño',         'B$',    1.000000),
  ('KYD', 'Dólar de Islas Caimán',  'CI$',   0.820000),
  ('RUB', 'Rublo ruso',             '₽',   91.000000),
  ('KZT', 'Tenge kazajo',           '₸',  449.000000),
  ('UZS', 'Som uzbeko',             "so'm",12700.000000),
  ('GEL', 'Lari georgiano',         '₾',    2.660000),
  ('AMD', 'Dram armenio',           '֏',  388.000000),
  ('AZN', 'Manat azerbaiyano',      '₼',    1.700000),
  ('BYN', 'Rublo bielorruso',       'Br',   3.260000),
  ('MDL', 'Leu moldavo',            'L',   17.700000),
  ('ALL', 'Lek albanés',            'L',  111.000000),
  ('MKD', 'Denar macedonio',        'ден', 57.500000),
  ('BAM', 'Marco convertible bosnio','KM',   1.810000),
  ('MNT', 'Tugrik mongol',          '₮', 3400.000000),
  ('MMK', 'Kyat birmano',           'K',  2100.000000),
  ('KHR', 'Riel camboyano',         '៛', 4100.000000),
  ('LAK', 'Kip laosiano',           '₭',21000.000000),
  ('BND', 'Dólar de Brunéi',        'B$',    1.340000),
  ('MOP', 'Pataca macaense',        'P',     8.040000),
  ('AFN', 'Afghani afgano',         '؋',   71.000000),
  ('IRR', 'Rial iraní',             '﷼',42000.000000),
  ('IQD', 'Dinar iraquí',           'ع.د', 1310.000000),
  ('SYP', 'Libra siria',            'LS', 2500.000000),
  ('YER', 'Rial yemení',            '﷼',  250.000000),
  ('LBP', 'Libra libanesa',         'ل.ل',89000.000000),
  ('ETB', 'Birr etíope',            'Br',   56.700000),
  ('TZS', 'Chelín tanzano',         'TSh',2520.000000),
  ('UGX', 'Chelín ugandés',         'USh',3780.000000),
  ('RWF', 'Franco ruandés',         'Fr', 1300.000000),
  ('ZMW', 'Kwacha zambiano',        'ZK',   25.300000),
  ('MZN', 'Metical mozambiqueño',   'MT',   63.900000),
  ('AOA', 'Kwanza angoleño',        'Kz',  832.000000),
  ('XOF', 'Franco CFA UEMOA',       'CFA', 615.000000)
ON CONFLICT (code) DO NOTHING;

-- =====================================================================
-- COMPLETE COUNTRIES LIST
-- (existing 30 from seed.sql will be skipped by ON CONFLICT DO NOTHING)
-- =====================================================================

INSERT INTO countries (code, name, currency) VALUES
  -- === AMERICAS: Caribbean ===
  ('AG', 'Antigua y Barbuda',       'XCD'),
  ('AW', 'Aruba',                   'USD'),
  ('BB', 'Barbados',                'BBD'),
  ('BS', 'Bahamas',                 'BSD'),
  ('BQ', 'Bonaire (Países Bajos)',  'USD'),
  ('CW', 'Curazao',                 'USD'),
  ('DM', 'Dominica',                'XCD'),
  ('GD', 'Granada',                 'XCD'),
  ('GP', 'Guadalupe',               'EUR'),
  ('HT', 'Haití',                   'HTG'),
  ('JM', 'Jamaica',                 'JMD'),
  ('KN', 'San Cristóbal y Nieves',  'XCD'),
  ('KY', 'Islas Caimán',            'KYD'),
  ('LC', 'Santa Lucía',             'XCD'),
  ('MF', 'San Martín (Francia)',    'EUR'),
  ('MQ', 'Martinica',               'EUR'),
  ('MS', 'Montserrat',              'XCD'),
  ('SX', 'Sint Maarten',            'USD'),
  ('TC', 'Islas Turks y Caicos',    'USD'),
  ('TT', 'Trinidad y Tobago',       'TTD'),
  ('VC', 'San Vicente y Granadinas','XCD'),
  ('VG', 'Islas Vírgenes Británicas','USD'),
  ('VI', 'Islas Vírgenes (EE. UU.)','USD'),

  -- === AMERICAS: Central & North ===
  ('BZ', 'Belice',                  'USD'),
  ('MX', 'México',                  'MXN'),  -- already in seed
  ('GT', 'Guatemala',               'GTQ'),
  ('HN', 'Honduras',                'HNL'),
  ('SV', 'El Salvador',             'USD'),
  ('NI', 'Nicaragua',               'NIO'),
  ('CR', 'Costa Rica',              'CRC'),
  ('PA', 'Panamá',                  'USD'),

  -- === AMERICAS: South ===
  ('CO', 'Colombia',                'COP'),
  ('VE', 'Venezuela',               'USD'),
  ('GY', 'Guyana',                  'USD'),
  ('SR', 'Surinam',                 'USD'),
  ('GF', 'Guayana Francesa',        'EUR'),
  ('BR', 'Brasil',                  'BRL'),
  ('EC', 'Ecuador',                 'USD'),
  ('PE', 'Perú',                    'PEN'),
  ('BO', 'Bolivia',                 'USD'),
  ('PY', 'Paraguay',                'USD'),
  ('CL', 'Chile',                   'CLP'),
  ('AR', 'Argentina',               'ARS'),
  ('UY', 'Uruguay',                 'USD'),
  ('FK', 'Islas Malvinas',          'GBP'),

  -- === EUROPE: Eurozone ===
  ('AT', 'Austria',                 'EUR'),
  ('BE', 'Bélgica',                 'EUR'),
  ('CY', 'Chipre',                  'EUR'),
  ('DE', 'Alemania',                'EUR'),
  ('EE', 'Estonia',                 'EUR'),
  ('ES', 'España',                  'EUR'),
  ('FI', 'Finlandia',               'EUR'),
  ('FR', 'Francia',                 'EUR'),
  ('GR', 'Grecia',                  'EUR'),
  ('HR', 'Croacia',                 'EUR'),
  ('IE', 'Irlanda',                 'EUR'),
  ('IT', 'Italia',                  'EUR'),
  ('LT', 'Lituania',                'EUR'),
  ('LU', 'Luxemburgo',              'EUR'),
  ('LV', 'Letonia',                 'EUR'),
  ('MT', 'Malta',                   'EUR'),
  ('NL', 'Países Bajos',            'EUR'),
  ('PT', 'Portugal',                'EUR'),
  ('SI', 'Eslovenia',               'EUR'),
  ('SK', 'Eslovaquia',              'EUR'),

  -- === EUROPE: Non-Eurozone ===
  ('AL', 'Albania',                 'ALL'),
  ('AD', 'Andorra',                 'EUR'),
  ('BA', 'Bosnia y Herzegovina',    'BAM'),
  ('BG', 'Bulgaria',                'BGN'),
  ('BY', 'Bielorrusia',             'BYN'),
  ('CH', 'Suiza',                   'CHF'),
  ('CZ', 'República Checa',         'CZK'),
  ('DK', 'Dinamarca',               'DKK'),
  ('GB', 'Reino Unido',             'GBP'),
  ('GI', 'Gibraltar',               'GBP'),
  ('HU', 'Hungría',                 'HUF'),
  ('IS', 'Islandia',                'ISK'),
  ('LI', 'Liechtenstein',           'CHF'),
  ('MC', 'Mónaco',                  'EUR'),
  ('MD', 'Moldavia',                'MDL'),
  ('ME', 'Montenegro',              'EUR'),
  ('MK', 'Macedonia del Norte',     'MKD'),
  ('NO', 'Noruega',                 'NOK'),
  ('PL', 'Polonia',                 'PLN'),
  ('RO', 'Rumania',                 'RON'),
  ('RS', 'Serbia',                  'RSD'),
  ('RU', 'Rusia',                   'RUB'),
  ('SE', 'Suecia',                  'SEK'),
  ('SM', 'San Marino',              'EUR'),
  ('TR', 'Turquía',                 'TRY'),
  ('UA', 'Ucrania',                 'UAH'),
  ('VA', 'Ciudad del Vaticano',     'EUR'),
  ('XK', 'Kosovo',                  'EUR'),

  -- === MIDDLE EAST ===
  ('AE', 'Emiratos Árabes Unidos',  'AED'),
  ('AF', 'Afganistán',              'AFN'),
  ('BH', 'Baréin',                  'BHD'),
  ('IQ', 'Irak',                    'IQD'),
  ('IR', 'Irán',                    'IRR'),
  ('IL', 'Israel',                  'ILS'),
  ('JO', 'Jordania',                'JOD'),
  ('KW', 'Kuwait',                  'KWD'),
  ('LB', 'Líbano',                  'LBP'),
  ('OM', 'Omán',                    'OMR'),
  ('PS', 'Palestina',               'ILS'),
  ('QA', 'Catar',                   'QAR'),
  ('SA', 'Arabia Saudita',          'SAR'),
  ('SY', 'Siria',                   'SYP'),
  ('YE', 'Yemen',                   'YER'),

  -- === ASIA: South ===
  ('BD', 'Bangladesh',              'BDT'),
  ('BT', 'Bután',                   'USD'),
  ('IN', 'India',                   'INR'),
  ('LK', 'Sri Lanka',               'LKR'),
  ('MV', 'Maldivas',                'USD'),
  ('NP', 'Nepal',                   'NPR'),
  ('PK', 'Pakistán',                'PKR'),

  -- === ASIA: East ===
  ('CN', 'China',                   'CNY'),
  ('HK', 'Hong Kong',               'HKD'),
  ('JP', 'Japón',                   'JPY'),
  ('KP', 'Corea del Norte',         'KRW'),
  ('KR', 'Corea del Sur',           'KRW'),
  ('MN', 'Mongolia',                'MNT'),
  ('MO', 'Macao',                   'MOP'),
  ('TW', 'Taiwán',                  'TWD'),

  -- === ASIA: Southeast ===
  ('BN', 'Brunéi',                  'BND'),
  ('ID', 'Indonesia',               'IDR'),
  ('KH', 'Camboya',                 'KHR'),
  ('LA', 'Laos',                    'LAK'),
  ('MM', 'Myanmar',                 'MMK'),
  ('MY', 'Malasia',                 'MYR'),
  ('PH', 'Filipinas',               'PHP'),
  ('SG', 'Singapur',                'SGD'),
  ('TH', 'Tailandia',               'THB'),
  ('TL', 'Timor-Leste',             'USD'),
  ('VN', 'Vietnam',                 'VND'),

  -- === ASIA: Central ===
  ('AM', 'Armenia',                 'AMD'),
  ('AZ', 'Azerbaiyán',              'AZN'),
  ('GE', 'Georgia',                 'GEL'),
  ('KG', 'Kirguistán',              'USD'),
  ('KZ', 'Kazajistán',              'KZT'),
  ('TJ', 'Tayikistán',              'USD'),
  ('TM', 'Turkmenistán',            'USD'),
  ('UZ', 'Uzbekistán',              'UZS'),

  -- === OCEANIA ===
  ('AU', 'Australia',               'AUD'),
  ('FJ', 'Fiyi',                    'USD'),
  ('FM', 'Micronesia',              'USD'),
  ('GU', 'Guam',                    'USD'),
  ('KI', 'Kiribati',                'AUD'),
  ('MH', 'Islas Marshall',          'USD'),
  ('MP', 'Islas Marianas del Norte','USD'),
  ('NC', 'Nueva Caledonia',         'USD'),
  ('NR', 'Nauru',                   'AUD'),
  ('NZ', 'Nueva Zelanda',           'NZD'),
  ('PF', 'Polinesia Francesa',      'USD'),
  ('PG', 'Papúa Nueva Guinea',      'USD'),
  ('PW', 'Palaos',                  'USD'),
  ('SB', 'Islas Salomón',           'USD'),
  ('TO', 'Tonga',                   'USD'),
  ('TV', 'Tuvalu',                  'AUD'),
  ('VU', 'Vanuatu',                 'USD'),
  ('WS', 'Samoa',                   'USD'),

  -- === AFRICA: North ===
  ('DZ', 'Argelia',                 'DZD'),
  ('EG', 'Egipto',                  'EGP'),
  ('LY', 'Libia',                   'USD'),
  ('MA', 'Marruecos',               'MAD'),
  ('MR', 'Mauritania',              'USD'),
  ('SD', 'Sudán',                   'USD'),
  ('SS', 'Sudán del Sur',           'USD'),
  ('TN', 'Túnez',                   'TND'),

  -- === AFRICA: West ===
  ('BF', 'Burkina Faso',            'XOF'),
  ('BJ', 'Benín',                   'XOF'),
  ('CI', 'Costa de Marfil',         'XOF'),
  ('CV', 'Cabo Verde',              'USD'),
  ('GH', 'Ghana',                   'GHS'),
  ('GM', 'Gambia',                  'USD'),
  ('GN', 'Guinea',                  'USD'),
  ('GW', 'Guinea-Bisáu',            'XOF'),
  ('LR', 'Liberia',                 'USD'),
  ('ML', 'Malí',                    'XOF'),
  ('MR', 'Mauritania',              'USD'),
  ('NE', 'Níger',                   'XOF'),
  ('NG', 'Nigeria',                 'NGN'),
  ('SL', 'Sierra Leona',            'USD'),
  ('SN', 'Senegal',                 'XOF'),
  ('TG', 'Togo',                    'XOF'),

  -- === AFRICA: East ===
  ('BI', 'Burundi',                 'USD'),
  ('DJ', 'Yibuti',                  'USD'),
  ('ER', 'Eritrea',                 'USD'),
  ('ET', 'Etiopía',                 'ETB'),
  ('KE', 'Kenia',                   'KES'),
  ('KM', 'Comoras',                 'USD'),
  ('MG', 'Madagascar',              'USD'),
  ('MU', 'Mauricio',                'USD'),
  ('MW', 'Malaui',                  'USD'),
  ('MZ', 'Mozambique',              'MZN'),
  ('RE', 'Reunión',                 'EUR'),
  ('RW', 'Ruanda',                  'RWF'),
  ('SC', 'Seychelles',              'USD'),
  ('SO', 'Somalia',                 'USD'),
  ('TZ', 'Tanzania',                'TZS'),
  ('UG', 'Uganda',                  'UGX'),
  ('YT', 'Mayotte',                 'EUR'),
  ('ZM', 'Zambia',                  'ZMW'),
  ('ZW', 'Zimbabue',                'USD'),

  -- === AFRICA: Central ===
  ('AO', 'Angola',                  'AOA'),
  ('CD', 'Congo (RDC)',             'USD'),
  ('CF', 'República Centroafricana','XAF'),
  ('CG', 'Congo (República)',       'XAF'),
  ('CM', 'Camerún',                 'XAF'),
  ('GA', 'Gabón',                   'XAF'),
  ('GQ', 'Guinea Ecuatorial',       'XAF'),
  ('ST', 'Santo Tomé y Príncipe',   'USD'),
  ('TD', 'Chad',                    'XAF'),

  -- === AFRICA: South ===
  ('BW', 'Botsuana',                'USD'),
  ('LS', 'Lesoto',                  'USD'),
  ('NA', 'Namibia',                 'ZAR'),
  ('SZ', 'Suazilandia',             'ZAR'),
  ('ZA', 'Sudáfrica',               'ZAR'),

  -- === SPECIAL / TERRITORIES ===
  ('GL', 'Groenlandia',             'DKK'),
  ('PM', 'San Pedro y Miquelón',    'EUR'),
  ('EH', 'Sahara Occidental',       'MAD')

ON CONFLICT (code) DO NOTHING;
